-- Auto-generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#242b33",
	base01 = "#1d2432",
	base02 = "#2d3239",
	base03 = "#474d56",
	base04 = "#a7abb4",
	base05 = "#cecfd5",
	base06 = "#565a60",
	base07 = "#484c53",

	-- Accent/Highlight Colors (base08 - base0F)
	-- These map to Red, Orange, Yellow, Green, Blue, Magenta, etc.
	base08 = "#ff8173",
	base09 = "#b9a1c7",
	base0A = "#9facbf",
	base0B = "#82aee2",
	base0C = "#dfc6ee",
	base0D = "#a3ceff",
	base0E = "#abd3ff",
	base0F = "#4476a9",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#02518c",
	fg = "#242b33",
})

set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#584168",
})

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#0a73be",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#0a73be",
})

vim.api.nvim_set_hl(0, "Keyword", {
	fg = "#4476a9",
})

vim.api.nvim_set_hl(0, "MsgArea", {
	bg = "#1d2432",
	fg = "#82aee2",
})
