-- Auto-generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#2e2630",
	base01 = "#2a202c",
	base02 = "#352e37",
	base03 = "#514954",
	base04 = "#b0a5b0",
	base05 = "#d2cad1",
	base06 = "#605861",
	base07 = "#514a51",

	-- Accent/Highlight Colors (base08 - base0F)
	-- These map to Red, Orange, Yellow, Green, Blue, Magenta, etc.
	base08 = "#ff7c6e",
	base09 = "#d59a9a",
	base0A = "#b4a2ba",
	base0B = "#c197d4",
	base0C = "#fcbdbd",
	base0D = "#e5baf9",
	base0E = "#e7bbfa",
	base0F = "#8b639f",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#603777",
	fg = "#2e2630",
})

set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#733c3e",
})

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#9f80ad",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#9f80ad",
})

vim.api.nvim_set_hl(0, "Keyword", {
	fg = "#8b639f",
})

vim.api.nvim_set_hl(0, "MsgArea", {
	bg = "#2a202c",
	fg = "#c197d4",
})
