-- Auto-generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#232b32",
	base01 = "#1a2830",
	base02 = "#2b3239",
	base03 = "#515a60",
	base04 = "#c6ccd3",
	base05 = "#e1e5ea",
	base06 = "#3f454b",
	base07 = "#474d53",

	-- Accent/Highlight Colors (base08 - base0F)
	-- These map to Red, Orange, Yellow, Green, Blue, Magenta, etc.
	base08 = "#ffb8af",
	base09 = "#d2c4ec",
	base0A = "#bccedd",
	base0B = "#98d2fc",
	base0C = "#eadeff",
	base0D = "#98d2fc",
	base0E = "#cae8ff",
	base0F = "#2a76a0",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#00638f",
	fg = "#232b32",
})

set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#5b4f78",
})

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#50a7dc",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#50a7dc",
})

vim.api.nvim_set_hl(0, "Keyword", {
	fg = "#2a76a0",
})

vim.api.nvim_set_hl(0, "MsgArea", {
	bg = "#1a2830",
	fg = "#98d2fc",
})
