# Core Colors
background            #232b32
foreground            #e1e5ea
selection_foreground  #98d2fc
selection_background  #004d72
cursor                #98d2fc
cursor_text_color     #232b32

# Regular Colors
color0  #232b32               
color1  #ffb8af                 
color2  #98d2fc               
color3  #d2c4ec              
color4  #cae8ff  
color5  #d4e7f7
color6  #bccedd             
color7  #e1e5ea            

# Bright Colors
color8  #474d53         
color9  #ffb8af                  
color10 #98d2fc                
color11 #d2c4ec               
color12 #cae8ff   
color13 #d4e7f7 
color14 #bccedd              
color15 #e1e5ea
